Repository flavray/avro-rs, pull requests merged in 2020-08, with the labels that each got.

#146 Make errors more fine-grained
  CHANGELOG.md
  Cargo.toml
  examples/to_value.rs
  migration_guide.md
  src/codec.rs
  src/de.rs
  src/decimal.rs
  src/decode.rs
  src/error.rs
  src/errors.rs
  src/lib.rs
  src/reader.rs
  src/schema.rs
  src/ser.rs
  src/types.rs
  src/util.rs
  src/writer.rs
  tests/io.rs
  tests/schema.rs
Labels: enhancement

#155 support to convert avro value to json value
  CHANGELOG.md
  src/error.rs
  src/types.rs
Labels: feature request

#153 Implement deserialize for Uuid
  Cargo.toml
  src/de.rs
Labels: bug, feature request
