Repository flavray/avro-rs, pull requests merged in 2020-07, with the labels that each got.

#136 Replace some manual from_str impls with strum
  src/codec.rs
  src/schema.rs
Labels: enhancement

#135 Move from failure to thiserror
  .pre-commit-config.yaml
  CHANGELOG.md
  Cargo.toml
  README.md
  README.tpl
  examples/to_value.rs
  migration_guide.md
  src/codec.rs
  src/de.rs
  src/decimal.rs
  src/decode.rs
  src/errors.rs
  src/lib.rs
  src/reader.rs
  src/schema.rs
  src/ser.rs
  src/types.rs
  src/util.rs
  src/writer.rs
  tests/io.rs
  tests/schema.rs
Labels: enhancement, feature request

#138 Move to GitHub actions
  .github/workflows/audit.yml
  .github/workflows/ci.yml
  .github/workflows/clippy.yml
  .travis.yml
  Cargo.toml
  README.md
  scripts/travis-test.sh
Labels: enhancement

#143 Add rustfmt.toml and consolidate imports
  benches/serde.rs
  benches/serde_json.rs
  benches/single.rs
  examples/benchmark.rs
  rustfmt.toml
  src/codec.rs
  src/de.rs
  src/decode.rs
  src/encode.rs
  src/lib.rs
  src/reader.rs
  src/schema.rs
  src/schema_compatibility.rs
  src/ser.rs
  src/types.rs
  src/util.rs
  src/writer.rs
  tests/io.rs
  tests/schema.rs
Labels: enhancement

#142 Move codec to use site
  src/codec.rs
Labels: enhancement

#144 Handle logical types in canonical form schema
  CHANGELOG.md
  src/schema.rs
  tests/schema.rs
Labels: feature request
