Repository flavray/avro-rs, pull requests merged in 2020-04, with the labels that each got.

#110 [Conflict Fix] Partial Rust Enum Serialization/Deserialization Support
  src/de.rs
  src/ser.rs
Labels: feature request

#111 Add support for logical types
  Cargo.toml
  README.md
  src/de.rs
  src/decimal.rs
  src/decode.rs
  src/duration.rs
  src/encode.rs
  src/lib.rs
  src/schema.rs
  src/types.rs
  src/writer.rs
Labels: enhancement, feature request

#114 Port benchmarks to criterion
  Cargo.toml
  benches/serde.rs
  benches/serde_json.rs
  benches/single.rs
  scripts/travis-test.sh
Labels: enhancement

#124 Fix clippy lints and add to CI
  Makefile
  scripts/travis-test.sh
  src/codec.rs
  src/de.rs
  src/decode.rs
  src/encode.rs
  src/lib.rs
  src/schema.rs
  src/types.rs
  src/writer.rs
Labels: enhancement
